import { Book } from './types';

export const CATEGORIES = [
  '全部分类',
  '学术写作',
  '科学技术',
  '开放科学',
  '经管励志',
  '人文社科',
  '文学艺术',
];

export const SHELVES = [
  '3楼前台侧',
  'A架-上层',
  'A架-中层',
  'A架-下层',
  'B架-上层',
  'B架-下层',
  'C架-新书区',
];

export const INITIAL_BOOKS: Book[] = [
  {
    id: 'b1',
    title: '设计心理学（4册套装）',
    author: '唐纳德·A·诺曼',
    translator: '小柯/张磊/何笑梅/欧秋杏',
    publisher: '中信出版社',
    description: '诺曼博士在《设计心理学》中强调以人为本的设计哲学，将认知心理学与行为学导入设计之中，帮助人们找到真正的问题与解决之道。',
    keywords: '认知心理学、品牌设计、创新管理',
    totalCopies: 1,
    availableCopies: 1,
    category: '科学技术',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-blue-600 to-indigo-800',
    addedDate: '2026-01-10'
  },
  {
    id: 'b2',
    title: '清单革命（经典版）',
    author: '[美]阿图·葛文德',
    translator: '无',
    publisher: '北京联合出版公司',
    description: '通过在医疗等领域的实践，作者掀起了一场清单革命，为大脑搭建起认知防护网，有效弥补人类与生俱来的记忆与注意力缺陷。',
    keywords: '风险管理、操作流程、复杂项目管理',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-emerald-600 to-teal-800',
    addedDate: '2026-01-12'
  },
  {
    id: 'b3',
    title: '怪诞行为学（1-6册套装）',
    author: '[美]丹·艾瑞里',
    translator: '无',
    publisher: '中信出版社',
    description: '本书一语道破我们不可思议的行为背后的原因，用轻松幽默的方式揭示非理性行为背后的经济与社会学力量。',
    keywords: '行为经济学、认知心理学、消费者行为学',
    totalCopies: 6,
    availableCopies: 5,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-amber-600 to-red-800',
    addedDate: '2026-01-15'
  },
  {
    id: 'b4',
    title: '向上管理·赢得高层支持的项目管理之道',
    author: '迈克尔·坎贝尔',
    translator: '王磊',
    publisher: '东方出版社',
    description: '讲述如何成功越过天然沟通鸿沟，建立并驾驭高层支持、公司政治生态、聆听技巧与决策提议等项目管理高阶能力。',
    keywords: '商业论证、高层沟通、资源协调',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-rose-600 to-purple-900',
    addedDate: '2026-01-18'
  },
  {
    id: 'b5',
    title: '问卷设计手册',
    author: '诺曼•布拉德伯恩/希摩•萨德曼/布莱恩•万辛克',
    translator: '赵锋',
    publisher: '重庆大学出版社',
    description: '实用性与理论性高度综合，提供各类题项、问卷整体注意事项提示、以及保证提示有效的理论根据和设计指南。',
    keywords: '问卷结构、量表设计、数据清理',
    totalCopies: 1,
    availableCopies: 1,
    category: '学术写作',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-sky-500 to-blue-700',
    addedDate: '2026-01-20'
  },
  {
    id: 'b6',
    title: '需求分析与系统设计',
    author: '麦沙塞克',
    translator: '无',
    publisher: '机械工业出版社',
    description: '论述需求分析与系统设计的迭代增量式过程，并介绍如何运用UML对大型信息系统模型进行面向对象分析设计。',
    keywords: '需求获取、数据库设计、面向对象设计',
    totalCopies: 1,
    availableCopies: 1,
    category: '科学技术',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-orange-500 to-amber-800',
    addedDate: '2026-01-22'
  },
  {
    id: 'b7',
    title: '改变世界的机器',
    author: '詹姆斯P.沃麦克/丹尼尔T.琼斯/丹尼尔·鲁斯',
    translator: '余锋/张冬/陶建刚',
    publisher: '机械工业出版社',
    description: '深刻阐述通用大批量生产系统与丰田精益生产系统的思维对比，展示向精益转型将如何深远影响并真正改变世界。',
    keywords: '精益生产、大规模生产、流程优化',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-purple-600 to-indigo-900',
    addedDate: '2026-01-24'
  },
  {
    id: 'b8',
    title: '商务电子邮件写作大全+英语表达句典（升级版）',
    author: '景凯文',
    translator: '凌恩英',
    publisher: '北京语言大学出版社',
    description: '涵盖英文商务电子邮件写作常识、20个商务主题100类交往活动模板，提供极其丰富的常用句典与表达。',
    keywords: '邮件写作、沟通礼仪、效率管理',
    totalCopies: 4,
    availableCopies: 4,
    category: '学术写作',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-teal-600 to-cyan-800',
    addedDate: '2026-01-26'
  },
  {
    id: 'b9',
    title: '人人都是产品经理2.0',
    author: '苏杰',
    translator: '无',
    publisher: '电子工业出版社',
    description: '定位在-1至3岁的产品经理，为泛产品新人、产品创业者、感兴趣的技术、设计、运营人员等量身定制。',
    keywords: '产品思维、用户挖掘、运营验证',
    totalCopies: 1,
    availableCopies: 1,
    category: '科学技术',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-cyan-700 to-blue-900',
    addedDate: '2026-01-28'
  },
  {
    id: 'b10',
    title: '物联网之云（云平台搭建与大数据处理）',
    author: '王见/赵帅/曾鸣/孙昊/曾凡太',
    translator: '无',
    publisher: '机械工业出版社',
    description: '阐述云计算基本概念、大数据处理方法与信息流程，给出了物联网云平台及雾计算的项目研发实战。',
    keywords: '物联网架构、云计算、数据挖掘、应用场景',
    totalCopies: 1,
    availableCopies: 1,
    category: '科学技术',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-red-500 to-rose-700',
    addedDate: '2026-01-30'
  },
  {
    id: 'b11',
    title: '前端架构（从入门到微前端）',
    author: '黄峰达',
    translator: '无',
    publisher: '电子工业出版社',
    description: '前端实施架构手册，从基础规范设计到采用微前端架构拆分复杂大型前端应用的全面系统设计指南。',
    keywords: '架构设计、构建工具、团队架构决策',
    totalCopies: 1,
    availableCopies: 1,
    category: '科学技术',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-blue-600 to-indigo-800',
    addedDate: '2026-02-01'
  },
  {
    id: 'b12',
    title: 'C Primer Plus（第6版中文版）',
    author: '[美]斯蒂芬·普拉达',
    translator: '姜佑',
    publisher: '人民邮电出版社',
    description: 'C语言经典自学与教学教材，适合需要系统学习C语言的初学者及希望巩固知识提高编程技术的程序员。',
    keywords: 'C语言、语法与编程结构、实践应用',
    totalCopies: 1,
    availableCopies: 1,
    category: '科学技术',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-emerald-600 to-teal-800',
    addedDate: '2026-02-03'
  },
  {
    id: 'b13',
    title: 'UI进化论——移动设备人机交互界面涉及',
    author: '周陟',
    translator: '无',
    publisher: '清华大学出版社',
    description: '涵盖交互与界面设计核心概念、移动设备体验工作流与实际案例，解析如何正确地将创意化为用户喜爱的内容。',
    keywords: '设计哲学、设计原则与要素、设计趋势',
    totalCopies: 1,
    availableCopies: 1,
    category: '科学技术',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-amber-600 to-red-800',
    addedDate: '2026-02-05'
  },
  {
    id: 'b14',
    title: '不列颠百科全书250周年纪念版',
    author: '美国不列颠百科全书公司',
    translator: '无',
    publisher: '中国大百科全书出版社',
    description: '最后一版纸质图书。涵盖早期珍稀词条精选、百余位诺奖得主等领袖级人物经典观点以及人类未来趋势的探讨。',
    keywords: '知识科普、百科全书',
    totalCopies: 1,
    availableCopies: 1,
    category: '人文社科',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-rose-600 to-purple-900',
    addedDate: '2026-02-07'
  },
  {
    id: 'b15',
    title: '测试架构师修炼之道·从测试工程师到测试架构师',
    author: '刘琛梅',
    translator: '无',
    publisher: '机械工业出版社',
    description: '核心讲述以“测试策略”串联各测试技术的理念，指导测试工程师构建系统化知识体系并快速升级。',
    keywords: '测试架构、测试策略制定、跨部门协作',
    totalCopies: 1,
    availableCopies: 1,
    category: '科学技术',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-sky-500 to-blue-700',
    addedDate: '2026-02-10'
  },
  {
    id: 'b16',
    title: '人生的84000种可能',
    author: '艾力',
    translator: '无',
    publisher: '湖南文艺出版社',
    description: '分享积极时间管理法、跨界华丽转身规划、职场难题应对策略，引导大众在面对迷茫时探索人生的无限潜能。',
    keywords: '自我探索、成长型思维、积极心理学',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-orange-500 to-amber-800',
    addedDate: '2026-02-12'
  },
  {
    id: 'b17',
    title: 'Encyclopedia of lipidomics',
    author: '无',
    translator: '无',
    publisher: '无',
    description: '脂质组学专业大百科。',
    keywords: '无',
    totalCopies: 1,
    availableCopies: 1,
    category: '开放科学',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-purple-600 to-indigo-900',
    addedDate: '2026-02-14'
  },
  {
    id: 'b18',
    title: 'Encyclopedia of Hydrological Sciences (1-3)',
    author: 'Anderson，Malcolm G.',
    translator: '无',
    publisher: 'Wiley',
    description: 'The definitive research level multi-volume treatment of hydrological sciences, providing scientifically rigorous information on all key aspects of the subject.',
    keywords: '水文学、水资源评估、科学参考',
    totalCopies: 1,
    availableCopies: 1,
    category: '开放科学',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-teal-600 to-cyan-800',
    addedDate: '2026-02-16'
  },
  {
    id: 'b19',
    title: 'Managing Performing living',
    author: 'Fredmund Malik',
    translator: '无',
    publisher: 'Campus Verlag',
    description: 'In this classic study, Malik offers professional advice for improving skills in organization, decision making, supervising, and budgeting.',
    keywords: '变革管理、决策与执行、团队赋能',
    totalCopies: 2,
    availableCopies: 2,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-cyan-700 to-blue-900',
    addedDate: '2026-02-18'
  },
  {
    id: 'b20',
    title: 'Peer Review and Manuscript Management in Scientific Journals',
    author: 'Irene Hames',
    translator: '无',
    publisher: 'Wiley-Blackwell',
    description: 'A comprehensive and concise guide to managing the peer review process, from manuscript submission to final decision in scientific journals.',
    keywords: '同行评审、科学出版、稿件管理',
    totalCopies: 6,
    availableCopies: 6,
    category: '开放科学',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-red-500 to-rose-700',
    addedDate: '2026-02-20'
  },
  {
    id: 'b21',
    title: 'The ACS Style Guide',
    author: 'Anne M. Coghill / Lorrin R. Garson',
    translator: '无',
    publisher: 'An American Chemical Society Publication',
    description: 'The definitive source for chemistry styling, ethics in communication, manuscript submission, and markup/formatting guidelines.',
    keywords: '学术交流、写作规范、投稿流程、开放获取',
    totalCopies: 6,
    availableCopies: 5,
    category: '学术写作',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-blue-600 to-indigo-800',
    addedDate: '2026-02-22'
  },
  {
    id: 'b22',
    title: '图书馆情报学概论',
    author: '于良芝',
    translator: '无',
    publisher: '国家图书馆出版社',
    description: '系统阐述信息需求、查询、获取与利用的现象、问题与信息组织技术原理，为中国学者带来先进视野与理论洞见。',
    keywords: '图书馆情报学、专业教材、信息需求分析',
    totalCopies: 1,
    availableCopies: 1,
    category: '人文社科',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-emerald-600 to-teal-800',
    addedDate: '2026-02-24'
  },
  {
    id: 'b23',
    title: 'LaTeX快速入门与提高',
    author: '李汉龙/隋英/韩婷',
    translator: '无',
    publisher: '国防工业出版社',
    description: '实例结合，展现中文LaTeX排版、相关配套软件及常用模板等实践，主要面向科技论文及数理公式排版需求。',
    keywords: 'LaTeX排版、操作手册、LaTeX编译方法',
    totalCopies: 1,
    availableCopies: 1,
    category: '学术写作',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-amber-600 to-red-800',
    addedDate: '2026-02-26'
  },
  {
    id: 'b24',
    title: '信息资源管理（第三版）',
    author: '马费成/赖茂生',
    translator: '无',
    publisher: '高等教育出版社',
    description: '规划教材，涵盖信息资源的历史沿革、获取检索、企业/政府信息资源管理、知识管理和优化配置等重点。',
    keywords: '信息资源管理、管理科学与工程',
    totalCopies: 1,
    availableCopies: 1,
    category: '学术写作',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-rose-600 to-purple-900',
    addedDate: '2026-02-28'
  },
  {
    id: 'b25',
    title: '绩效管理从入门到精通',
    author: '胡劲松',
    translator: '无',
    publisher: '清华大学出版社',
    description: '讲解绩效管理的理念与实践，通过方法论、工具与模板，提供全方位具有可操作性的企业战略绩效解决方案。',
    keywords: '绩效管理、企业绩效、战略性绩效管理',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-sky-500 to-blue-700',
    addedDate: '2026-03-01'
  },
  {
    id: 'b26',
    title: '华为绩效管理法',
    author: '汪廷云',
    translator: '无',
    publisher: '广东经济出版社',
    description: '系统研究华为绩效管理流程特点，并结合其在华为工作多年的实践经历与案例，让其绩效管理学得会。',
    keywords: '华为绩效管理、绩效管理体系、管理实战案例',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-orange-500 to-amber-800',
    addedDate: '2026-03-03'
  },
  {
    id: 'b27',
    title: 'TOOLSFITANS巨人的工具',
    author: '[美]蒂姆·费里斯/[美]蒂莫西·费里斯',
    translator: '杨清波',
    publisher: '中信出版社',
    description: '取材于上百位行业精英的访谈，提炼出“健康”、“财富”与“智慧”三大相辅相成的生活与成功实用工具。',
    keywords: '精英访谈、个人提升、生活方式设计',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-purple-600 to-indigo-900',
    addedDate: '2026-03-05'
  },
  {
    id: 'b28',
    title: '编辑人的世界',
    author: '[美]杰拉尔德·格罗斯',
    translator: '齐若兰',
    publisher: '北京十月文艺出版社',
    description: '收录38位知名编辑人撰文，带领读者全景进入主流出版及内容创作者的奇妙世界，领悟有价值之内容的塑造过程。',
    keywords: '编辑思维、内容塑造与表达、跨领域沟通协作',
    totalCopies: 1,
    availableCopies: 1,
    category: '学术写作',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-teal-600 to-cyan-800',
    addedDate: '2026-03-07'
  },
  {
    id: 'b29',
    title: '信息检索',
    author: '黄如花/胡永生/程银桂',
    translator: '无',
    publisher: '武汉大学出版社',
    description: '系统讲解网络信息检索、数据库利用、信息查询的基础理论方法、计算机和光盘检索技术以及信息咨询评价。',
    keywords: '信息管理与素养、网络信息资源、检索工具与方法',
    totalCopies: 1,
    availableCopies: 1,
    category: '学术写作',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-cyan-700 to-blue-900',
    addedDate: '2026-03-09'
  },
  {
    id: 'b30',
    title: '信息管理学基础',
    author: '马费成/宋恩梅/赵一鸣',
    translator: '无',
    publisher: '武汉大学出版社',
    description: '从信息交流、获取、组织、系统与服务等方面探讨人类管理信息的规律，结合数字环境分析最新前沿演变。',
    keywords: '信息管理、信息系统与信息服务、数字环境',
    totalCopies: 1,
    availableCopies: 1,
    category: '学术写作',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-red-500 to-rose-700',
    addedDate: '2026-03-11'
  },
  {
    id: 'b31',
    title: '图书馆学基础',
    author: '吴慰慈',
    translator: '无',
    publisher: '高等教育出版社',
    description: '阐述图书馆学研究对象、网络信息资源开发、文献数字化及知识管理，对虚拟与转型策略等前沿问题深入解析。',
    keywords: '图书馆学、信息资源管理、数字图书馆',
    totalCopies: 1,
    availableCopies: 1,
    category: '人文社科',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-blue-600 to-indigo-800',
    addedDate: '2026-03-13'
  },
  {
    id: 'b32',
    title: '员工激励的88个最佳手段',
    author: '高宇杰',
    translator: '无',
    publisher: '广东经济出版社',
    description: '针对员工多层级需求，介绍一系列实用的奖惩及员工激励手段，通过故事案例为管理者强化企业绩效。',
    keywords: '员工激励、人力资源管理、领导力',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-emerald-600 to-teal-800',
    addedDate: '2026-03-15'
  },
  {
    id: 'b33',
    title: '情商',
    author: '[美]丹尼尔·戈尔曼',
    translator: '杨春晓',
    publisher: '中信出版社',
    description: '突破性研究，说明高智商不一定成功，而高情商（自我意识、自律与同理心）才是决定幸福与卓越的核心。',
    keywords: '情商、自我意识、个人发展',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-amber-600 to-red-800',
    addedDate: '2026-03-17'
  },
  {
    id: 'b34',
    title: '出版专业实务（初级）2020年版',
    author: '国家新闻出版署出版专业资格考试办公室',
    translator: '无',
    publisher: '崇文书局；中国书籍出版社',
    description: '备考辅导及在职学习教材，讲述理论在实际出版业务中的应会操作，体现出版工作的规范性要求。',
    keywords: '出版专业资格考试、规范性操作、从业参考',
    totalCopies: 1,
    availableCopies: 1,
    category: '学术写作',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-rose-600 to-purple-900',
    addedDate: '2026-03-19'
  },
  {
    id: 'b35',
    title: '牛津高阶英汉双解词典',
    author: '[英]霍恩比',
    translator: '李旭影等',
    publisher: '商务印书馆',
    description: '公认经典的英汉词典，将会话与写作功能融入学习型词典中，全面提升查阅、听说与英文交流学习。',
    keywords: '学习型词典、牛津高阶英汉双解词典',
    totalCopies: 1,
    availableCopies: 1,
    category: '文学艺术',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-sky-500 to-blue-700',
    addedDate: '2026-03-21'
  },
  {
    id: 'b36',
    title: '有关出版的法律法规选编（2021版）',
    author: '国家新闻出版署出版专业资格考试办公室编',
    translator: '无',
    publisher: '大象出版社；中国书籍出版社',
    description: '汇集全国出版行业的核心法律法规、条例与管理规定，是应试必考及在职规范化出版实务的标准法条合集。',
    keywords: '出版专业资格考试、法律法规选编、出版法律法规',
    totalCopies: 1,
    availableCopies: 1,
    category: '学术写作',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-orange-500 to-amber-800',
    addedDate: '2026-03-23'
  },
  {
    id: 'b37',
    title: '改变提问，改变人生——12个改善生活与工作的有力工具',
    author: '[美]梅若李·亚当斯',
    translator: '秦瑛',
    publisher: '机械工业出版社',
    description: '介绍提问式思维：通过将思维聚焦于“学习”而非“评判”，改善个人觉察、情绪重构以取得卓越结果。',
    keywords: '提问式思维、ABCC法则、思维模式转换',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-purple-600 to-indigo-900',
    addedDate: '2026-03-25'
  },
  {
    id: 'b38',
    title: '六顶思考帽',
    author: '[英]爱德华德·博诺',
    translator: '马睿',
    publisher: '中信出版社',
    description: '经典的思考及讨论框架，将逻辑、情感、创造与信息等区分开来，提升对话、会议成效与多维沟通质量。',
    keywords: '平性思维、思维管理工具、团队沟通与生产力',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-teal-600 to-cyan-800',
    addedDate: '2026-03-27'
  },
  {
    id: 'b39',
    title: '科技文献检索',
    author: '赖茂生等编',
    translator: '无',
    publisher: '北京大学出版社',
    description: '系统阐述科技文献检索的基本原理、叙词及自动标引等方法，系统掌握重要的数据库工具。',
    keywords: '科技文献检索、检索原理与方法、教材与专业参考书',
    totalCopies: 1,
    availableCopies: 1,
    category: '学术写作',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-cyan-700 to-blue-900',
    addedDate: '2026-03-29'
  },
  {
    id: 'b40',
    title: '语言的突破',
    author: '戴尔·卡内基',
    translator: '无',
    publisher: '中国妇女出版社',
    description: '卡内基经典口才与当众演讲指导，教会人们如何建立自信，大方得体地发表见解并说服他人。',
    keywords: '沟通与人际关系、说服力与影响力、公开演讲',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-red-500 to-rose-700',
    addedDate: '2026-04-01'
  },
  {
    id: 'b41',
    title: '原则——生活和工作',
    author: 'RayDalio',
    translator: '陳世杰/諶悠文/戴至中',
    publisher: '商業周刊',
    description: '达利欧分享桥水基金四十年的顶尖管理智慧，建立起极度求真与极其透明的工作体系与为人处世原则。',
    keywords: '创意择优、可信度加权决策、经验提炼与进化',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-blue-600 to-indigo-800',
    addedDate: '2026-04-03'
  },
  {
    id: 'b42',
    title: '从HR到HRBP——成为专业HRBP的七大实战场景与基本技能',
    author: '王海',
    translator: '无',
    publisher: '人民邮电出版社',
    description: '指导HR紧贴业务，做好招聘规划、搭建人才梯队、推动组织发展、并打造出非职权影响力。',
    keywords: 'HRBP、人才梯队、组织发展',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-emerald-600 to-teal-800',
    addedDate: '2026-04-05'
  },
  {
    id: 'b43',
    title: '出版专业基础（初级）2020年版',
    author: '国家新闻出版署出版专业资格考试办公室',
    translator: '无',
    publisher: '崇文书局',
    description: '全国出版资格考试基础辅导教材，系统掌握编辑与出版流程基础知识及职业守则。',
    keywords: '出版专业基础、资格考试辅导教材',
    totalCopies: 1,
    availableCopies: 1,
    category: '学术写作',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-amber-600 to-red-800',
    addedDate: '2026-04-07'
  },
  {
    id: 'b44',
    title: '文案的基本修养',
    author: '东东枪',
    translator: '无',
    publisher: '中信出版社',
    description: '为广告及创意初学者撰写，侧重于创意的底层逻辑认识与思维构建，解答如何辨别对错好坏的创意。',
    keywords: '广告创意、创意哲学',
    totalCopies: 1,
    availableCopies: 1,
    category: '文学艺术',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-rose-600 to-purple-900',
    addedDate: '2026-04-10'
  },
  {
    id: 'b45',
    title: '卓有成效的管理者7',
    author: '[美]彼得·德鲁克',
    translator: '许是祥',
    publisher: '机械工业出版社',
    description: '德鲁克认为每一位决策并为组织贡献的知识工作者都是管理者，深入论述了管理者如何自我学习做到成效。',
    keywords: '管理学经典、组织行为学、自我管理与职业发展',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-sky-500 to-blue-700',
    addedDate: '2026-04-12'
  },
  {
    id: 'b46',
    title: '任正非管理的真相',
    author: '孙力科',
    translator: '无',
    publisher: '企业管理出版社',
    description: '系统梳理任正非与华为的标志性管理思想，探讨华为如何从2万元起步走向全球通信设备巨头并实现高速成长。',
    keywords: '任正非管理思想、华为管理实践、企业成长',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-orange-500 to-amber-800',
    addedDate: '2026-04-15'
  },
  {
    id: 'b47',
    title: '华为的管理模式（第3版）',
    author: '王伟立/李慧群',
    translator: '无',
    publisher: '海天出版社',
    description: '探讨华为特有的土狼式竞争与内部体系，复原流程化管理、变革机制、以及供应链运作的全方位管理模式。',
    keywords: '华为管理模式、狼式管理、企业扩张与竞争策略',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-purple-600 to-indigo-900',
    addedDate: '2026-04-17'
  },
  {
    id: 'b48',
    title: '非上市公司的股权激励一本通（第2版）',
    author: '单海洋',
    translator: '无',
    publisher: '北京大学出版社',
    description: '上千家咨询实战总结，传授如何为非上市公司量身制定并落地实施合法有效的股权激励整体方案。',
    keywords: '非上市公司股权激励、实战咨询与案例、激励方案 design',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-teal-600 to-cyan-800',
    addedDate: '2026-04-19'
  },
  {
    id: 'b49',
    title: '任正非内部讲话——关键时，任正非说了什么',
    author: '屠爽',
    translator: '无',
    publisher: '新世界出版社',
    description: '分析华为发展关键节点上任正非所起的作用，通过具有激情和前瞻性的内部讲话带领企业在危机中把握微光。',
    keywords: '任正非内部讲话、领导力与危机管理、企业管理智慧',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-cyan-700 to-blue-900',
    addedDate: '2026-04-21'
  },
  {
    id: 'b50',
    title: '以奋斗者为本——华为公司人力资源管理纲要',
    author: '黄卫伟',
    translator: '无',
    publisher: '中信出版社',
    description: '传承基本法思想，全面展现华为二十余年凝聚干部队伍、薪酬分配、晋升和奋斗者价值考核的管理精髓。',
    keywords: '以奋斗者为本、企业实践、价值分配',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-red-500 to-rose-700',
    addedDate: '2026-04-23'
  },
  {
    id: 'b51',
    title: '蓝海战略（扩展版）',
    author: '[美]W.钱·金/[美]勒妮·莫博涅',
    translator: '吉宓',
    publisher: '商务印书馆',
    description: '经典战略书：企业不能仅仅停留在血腥厮杀的“红海”，而是应当通过价值创新开创蕴含庞大潜在需求的新蓝海。',
    keywords: '蓝海战略、价值创新、战略布局',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-blue-600 to-indigo-800',
    addedDate: '2026-04-25'
  },
  {
    id: 'b52',
    title: '华为的人力资源管理（第3版）',
    author: '张继辰/文丽颜',
    translator: '无',
    publisher: '海天出版社',
    description: '结合理论与实际，解析连业内专家也称赞的华为人力资源组织架构、员工选人战略和薪酬分配奇招。',
    keywords: '华为人力资源管理、人力资源架构与机制',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-emerald-600 to-teal-800',
    addedDate: '2026-04-27'
  },
  {
    id: 'b53',
    title: '不懂带人，你就自己干到死——把身边的庸才变成干将',
    author: '路易斯·卡弗曼',
    translator: '张甜',
    publisher: '中国友谊出版公司',
    description: '提倡管理者去培养一群善于解决问题的人，学会合理授权，不为责任找借口，激发下属的自主能动性。',
    keywords: '培养下属、管理者沟通与干预、团队管理实践',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-amber-600 to-red-800',
    addedDate: '2026-04-29'
  },
  {
    id: 'b54',
    title: '策略思维——商界、政界及日常生活中的策略竞争',
    author: '阿维纳什·K·迪克西特/巴里·小奈尔伯夫',
    translator: '王尔山译',
    publisher: '中国人民大学出版社',
    description: '博弈论经典著作。教你认识人生是一场永不停息的决策互动游戏，学会策略性思考并扩大人生赢面。',
    keywords: '博弈论、策略性思考、互动决策',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-rose-600 to-purple-900',
    addedDate: '2026-05-01'
  },
  {
    id: 'b55',
    title: '组织文化与领导力（第五版）',
    author: '埃德加·沙因/彼得·沙因',
    translator: '陈劲/贾筱',
    publisher: '中国人民大学出版社',
    description: '管理大师经典：界定组织文化概念与三层次模型，探讨领导力在塑造、维护和变革组织文化中的关键作用。',
    keywords: '组织文化、领导力与文化塑造、文化变革管理',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-sky-500 to-blue-700',
    addedDate: '2026-05-03'
  },
  {
    id: 'b56',
    title: '老HR手把手教你搞定HR管理（初级版）',
    author: '应秋月',
    translator: '无',
    publisher: '机械工业出版社',
    description: '提供大量基础HR实战案例与具体的操作步骤，帮助职场小白掌握基本法律依据和防范员工管理纠纷。',
    keywords: 'HR管理实战、企业管理、初级HR从业者',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-orange-500 to-amber-800',
    addedDate: '2026-05-05'
  },
  {
    id: 'b57',
    title: '老HR手把手教你搞定HR管理（中级版）',
    author: '应秋月',
    translator: '无',
    publisher: '机械工业出版社',
    description: '独创123管理法，引导HR将人力资源规划与公司经营活动深度揉合，真正发挥绩效管理的硬性价值。',
    keywords: '123管理法、HR与经营融合、组织人力效能',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-purple-600 to-indigo-900',
    addedDate: '2026-05-07'
  },
  {
    id: 'b58',
    title: '老HR手把手教你搞定HR管理（高级版）',
    author: '应秋月',
    translator: '无',
    publisher: '机械工业出版社',
    description: '提出高级总监应布局的“六步棋”与“三件事”，附赠自创的人力资源管理成熟度评估检查模型。',
    keywords: '辅佐企业经营、人力资源管理成熟度模型、组织人力效能体系',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-teal-600 to-cyan-800',
    addedDate: '2026-05-10'
  },
  {
    id: 'b59',
    title: '华为的企业文化（第3版）',
    author: '赵海涛//陈广',
    translator: '无',
    publisher: '海天出版社',
    description: '全景展示华为在时代潮流跌宕起伏中始终坚持的独特奋斗者文化和企业内核。',
    keywords: '华为企业文化、世界级企业、逆势增长与全球化',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-cyan-700 to-blue-900',
    addedDate: '2026-05-12'
  },
  {
    id: 'b60',
    title: '企业管理',
    author: '于莉/王吉方编',
    translator: '无',
    publisher: '电子工业出版社',
    description: '遵循必须与实用原则，整合市场经济、企业决策、营销、生产、质量以及人力资源管理等基本实务。',
    keywords: '企业管理综合教材、市场经济、企业实务',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-red-500 to-rose-700',
    addedDate: '2026-05-15'
  },
  {
    id: 'b61',
    title: '战略 management——概念与案例',
    author: '迈克尔·希特/R.杜安·爱尔兰/罗伯特·霍斯基森',
    translator: '刘刚/梁晗/耿天成',
    publisher: '中国人民大学出版社',
    description: '权威经典教程，涵盖战略分析工具、行业竞争动态与公司经典案例，展示当代复杂市场的管理全貌。',
    keywords: '战略管理、案例与实践、跨层级教学参考',
    totalCopies: 3,
    availableCopies: 3,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-blue-600 to-indigo-800',
    addedDate: '2026-05-17'
  },
  {
    id: 'b62',
    title: 'Linux从入门到精通（第2版）',
    author: '刘忆智',
    translator: '无',
    publisher: '清华大学出版社',
    description: '零门槛的Linux系统自学精通指南，提供丰富的环境实操上机示例与常用管理指令，适合初学者及系统管理员。',
    keywords: 'Linux入门与精通、系统管理员',
    totalCopies: 1,
    availableCopies: 1,
    category: '科学技术',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-emerald-600 to-teal-800',
    addedDate: '2026-05-19'
  },
  {
    id: 'b63',
    title: '薪酬管理（第11版）',
    author: '[美]巴里·格哈特',
    translator: '成得礼',
    publisher: '中国人民大学出版社',
    description: '经典教材，以米尔科维奇薪酬模型为核心，探讨内部一致性、外部竞争、福利体系与整体薪酬管理。',
    keywords: '薪酬管理、米尔科维奇模型、战略人力资源管理',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-amber-600 to-red-800',
    addedDate: '2026-05-21'
  },
  {
    id: 'b64',
    title: '沟通的艺术——看入人里，看出人外',
    author: '[美]罗纳德·B·阿德勒/拉塞尔·F·普罗科特',
    translator: '黄素菲/李恩/王敏',
    publisher: '北京联合出版公司',
    description: '分为看入人里、看出人外、看人之间，全景分析沟通者的知觉情绪、语言运用、倾听与冲突处理技巧。',
    keywords: '人际沟通、倾听、关系与冲突管理',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-rose-600 to-purple-900',
    addedDate: '2026-05-23'
  },
  {
    id: 'b65',
    title: '卡耐基沟通的艺术与处世智慧',
    author: '戴尔·卡耐基',
    translator: '王红星',
    publisher: '中国华侨出版社',
    description: '探讨克服畏惧、树立自信的当众表达法，指导大众在日常生活与商务场景中博得赞誉，拓展成功人际网络。',
    keywords: '沟通的艺术、自信建立、人际关系处理',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-sky-500 to-blue-700',
    addedDate: '2026-05-25'
  },
  {
    id: 'b66',
    title: '美国大学英语写作',
    author: '[美]John Langan',
    translator: '无',
    publisher: '外语教学与研究出版社',
    description: '系统实用的英文写作教材，系统讲解写作流程、9种常见段落写作方法与遣词造句的核心规范技巧。',
    keywords: '大学英语写作、写作技巧与修辞、学术诚信',
    totalCopies: 1,
    availableCopies: 1,
    category: '文学艺术',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-orange-500 to-amber-800',
    addedDate: '2026-05-27'
  },
  {
    id: 'b67',
    title: '生理学（第9版）',
    author: '王庭槐',
    translator: '无',
    publisher: '人民卫生出版社',
    description: '医学领域经典权威教材，涵盖细胞生物电、血液循环、呼吸系统、消化以及内分泌与生殖生理学核心知识体系。',
    keywords: '生理学、教材用书',
    totalCopies: 1,
    availableCopies: 1,
    category: '科学技术',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-purple-600 to-indigo-900',
    addedDate: '2026-05-29'
  },
  {
    id: 'b68',
    title: '会计学基础（第7版）',
    author: 'Rober N. Anthony / Leslie K. Pearlman',
    translator: '无',
    publisher: '清华大学出版社',
    description: '涵盖财务记录、资产负债、收入费用、非流动资产、现金流量表和财务指标分析等，通过案例强化基础。',
    keywords: '会计学基础、教学参考、案例教学',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-teal-600 to-cyan-800',
    addedDate: '2026-06-01'
  },
  {
    id: 'b69',
    title: '手把手教你读财报（新准则升级版）',
    author: '唐朝',
    translator: '无',
    publisher: '中国经济出版社',
    description: '从投资者视角出发，摒弃繁杂术语与晦涩公式，以真实案例分析财报的排雷技巧与实战估值经验。',
    keywords: '财报阅读指南、会计准则、投资者视角',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-cyan-700 to-blue-900',
    addedDate: '2026-06-03'
  },
  {
    id: 'b70',
    title: '世界上最简单的会计书',
    author: '[美]达雷尔·穆利斯/[美]朱迪丝·奥洛夫',
    translator: '黄屹',
    publisher: '机械工业出版社',
    description: '以开设柠檬汁摊为背景，通俗易懂地普及资产、负债、盈余、存货、应收应付款等核心会计概念。',
    keywords: '会计入门、场景教学、会计概念',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-red-500 to-rose-700',
    addedDate: '2026-06-05'
  },
  {
    id: 'b71',
    title: '信息简史',
    author: '[美]詹姆斯·格雷克',
    translator: '高博',
    publisher: '人民邮电出版社',
    description: '展现人类与信息遭遇的波澜壮阔历史，从非洲鼓语到文字发明、摩尔斯电码和香农奠基的现代信息论。',
    keywords: '信息史、香农信息论、跨学科信息观',
    totalCopies: 1,
    availableCopies: 1,
    category: '人文社科',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-blue-600 to-indigo-800',
    addedDate: '2026-06-07'
  },
  {
    id: 'b72',
    title: '关键对话',
    author: '王紫威编',
    translator: '无',
    publisher: '中国纺织出版社',
    description: '阐述在面对高风险、情绪敏感话题时如何进行顺畅交流与良性表达，大幅提升沟通胜任力与处世艺术。',
    keywords: '语言表达、口才训练、沟通技巧',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-emerald-600 to-teal-800',
    addedDate: '2026-06-09'
  },
  {
    id: 'b73',
    title: '商务英语写作实力精解（第七版）',
    author: 'Shirley Taylor',
    translator: '无',
    publisher: '外语教学与研究出版社',
    description: '商务英语写作实用手册，包含多种类型的商务书信及电邮撰写实例，助力建立专业高质的职场沟通。',
    keywords: '商务英语写作、实例精解、商务沟通',
    totalCopies: 1,
    availableCopies: 1,
    category: '学术写作',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-amber-600 to-red-800',
    addedDate: '2026-06-11'
  },
  {
    id: 'b74',
    title: '金字塔原理大全集',
    author: '芭芭拉·明托',
    translator: '无',
    publisher: '南海出版公司',
    description: '提出“结论先行、以上统下、归类分组、逻辑递进”的经典思维管理法则，掌握重点突出、逻辑清晰的表达精髓。',
    keywords: '逻辑思维、结构化表达、受众导向沟通',
    totalCopies: 1,
    availableCopies: 1,
    category: '经管励志',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-rose-600 to-purple-900',
    addedDate: '2026-06-13'
  },
  {
    id: 'b75',
    title: 'Word其实不简单，这样用就[对]了',
    author: '张卓',
    translator: '无',
    publisher: '中国水利水电出版社',
    description: '从版式规范、长文档处理、图文混排等多角度入手，彻底解析Word高级排版与高效率办公技巧。',
    keywords: 'word基础操作、使用技巧、办公软件',
    totalCopies: 1,
    availableCopies: 1,
    category: '科学技术',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-sky-500 to-blue-700',
    addedDate: '2026-06-15'
  },
  {
    id: 'b76',
    title: '剑桥中级英语语法练习（第四版中文版）',
    author: '雷蒙德·墨菲',
    translator: '无',
    publisher: '外语教学与研究出版社',
    description: '享誉全球的英语语法经典练习与自学指南，结构清晰，适合中级英语学习者在练习中巩固语法基础。',
    keywords: '英语学习教材、语法练习与参考',
    totalCopies: 1,
    availableCopies: 1,
    category: '文学艺术',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-orange-500 to-amber-800',
    addedDate: '2026-06-17'
  },
  {
    id: 'b77',
    title: '剑桥初级英语语法（第三版中文版）',
    author: '雷蒙德·墨菲',
    translator: '无',
    publisher: '外语教学与研究出版社',
    description: '针对初学者设计的英语基础语法参考练习书，提供清晰简明的一页讲解一页练习，大幅提高自学效率。',
    keywords: '英语学习教材、语法练习与参考',
    totalCopies: 1,
    availableCopies: 1,
    category: '文学艺术',
    shelfLocation: '3楼前台侧',
    coverBg: 'from-purple-600 to-indigo-900',
    addedDate: '2026-06-19'
  }
];
